### ISSUE TITLE
我搞了个LOGO

### ISSUE THREAD

**Issue by kain365** [GodotHan/WeDot#6]
把机器人头换成了猫头
![6a04bd435729702696108a248779fece7595c14315f5892f605f9317af1373ea](https://github.com/user-attachments/assets/fcbdc3a4-9675-4dbb-aab2-19ea8c722652)

**Comment by kain365** [comment]
![e30124180d9256df037ef3b56db3f7cfd767b75ac70da47c10e1e335bc914410](https://github.com/user-attachments/assets/190cb481-56eb-4ee7-9475-ed34dc2d4878)

**Comment by kain365** [comment]
> 把机器人头换成了猫头 ![6a04bd435729702696108a248779fece7595c14315f5892f605f9317af1373ea](https://private-user-images.githubusercontent.com/25736063/378195586-fcbdc3a4-9675-4dbb-aab2-19ea8c722652.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDk0MDYsIm5iZiI6MTcyOTQ0OTEwNiwicGF0aCI6Ii8yNTczNjA2My8zNzgxOTU1ODYtZmNiZGMzYTQtOTY3NS00ZGJiLWFhYjItMTllYThjNzIyNjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE4MzE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMjVmZGRiNDgxNmExODU0N2JmN2YwMzE5OWMxNDk1OTgwNWIxMDhlZDc1Y2NiNjUxM2EyMTAxMTE2YmY5MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KqpHeea2EjOlE7UjPuaAO81wl9iRHO5o2xAOy6V2eWc)

**Comment by PJ-568** [comment]
很抱歉，我们没能采用你的 logo，不过别灰心，期待未来有更多的机会可以合作。你的设计很有创意，谢谢你的提案。
